version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "msk-pyconsumer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-zez2v5ke4nzp"
s3_prefix = "msk-pyconsumer"
region = "us-east-2"
profile = "ambassador"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "MSKArn=\"arn:aws:kafka:us-east-2:574715127331:cluster/msk-dev01-cluster/90a0b109-536a-4051-89cc-9b4290145dc9-2\" MSKTopic=\"adam\""
